### ISSUE TITLE
Reservierte Sitze-IDs bei Reservierung

### ISSUE THREAD

**Issue by kollb** [JanMalch/kino#100]
Brauchen wir noch die Änderung der Sitz-IDs im Frontend? Imo kann das raus

**Comment by MarekHohmann** [comment]
Hatten uns glaub drauf geeinigt, dass Reservierungen nicht geändert werden können sollen, sondern man Reservierungen nur löscht und dann neue anlegt.

An der Kinokasse wirste ja auch kaum ne Reservierung ändern, wenn da auf einmal ein Platz weniger benötigt wird, sondern einfach ne Karte weniger ausgeben.

Fazit: Update kann mMn. raus, dann spart man sich da die Reservierung.
Alternative: Gleiche Kinosaal Übersicht wie bei der Reservierung durch einen User (weis aber nicht wie man das macht, das ist Angular-Magic, müsste mich da erst reinfuchsen).

**Comment by JanMalch** [comment]
![Aktualisierte Admin-Übersicht](https://user-images.githubusercontent.com/25508038/59878440-92e85800-93a8-11e9-83f3-06151c47d125.PNG)
