### ISSUE TITLE
ForbiddenException: User not authorized

### ISSUE THREAD

**Issue by JanMalch** [JanMalch/kino#105]
`ForbiddenException: User not authorized` bei meine Reservierungen. Grund unklar.

---

Ich hab folgendes gemacht:

- Passwort "erfolgreich" geändert für customer (Siehe auch #71 )
- umloggen auf customer1 (erfolgreich, kriege auch meinen Namen angezeigt, etc.)
- `Forbidden` Fehler beim Aufruf meiner Reservierungen

**Comment by JanMalch** [comment]
Might be related to #110

**Comment by kollb** [comment]
getAllPresentations hat RolesAllowed auf Moderator. Remove oder runter auf Customer fixt das Problem.
