### ISSUE TITLE
Cleanup vor Abgabe

### ISSUE THREAD

**Issue by MarekHohmann** [JanMalch/kino#130]
- [x] Dummy Daten anpassen (Datum)
- [x] ~Quicklinks entfernen~ (https://github.com/JanMalch/kino/issues/130#issuecomment-504061406)
- [x] Default Admin Zugangsdaten dokumentieren

**Comment by JanMalch** [comment]
Oder Quicklinks einklappen per default?
Ist klar, dass das nur für Test ist, aber ist doch auch praktisch für ihn?

**Comment by kollb** [comment]
Ich würde es auch so lassen. Einfach einen roten Text schreiben for testing not for production usage
