### ISSUE TITLE
Delete orphans in OneToMany relationships

### ISSUE THREAD

**Issue by JanMalch** [JanMalch/kino#22]
Muss für jeden Use-Case individuell entschieden werden.
z.B. wenn eine Movie Entity gelöscht wird, sollten auch alle verknüpften Presentations gelöscht werden.

---

#### https://stackoverflow.com/a/5642615

>If professions are only part of this relationship, then you can guarantee that when a profession is removed from the User's set it will also be removed from the database by turning on orphanRemoval on the OneToMany side of the relationship.
```java
@OneToMany(mappedBy="user", cascade=CascadeType.ALL, orphanRemoval=true)
private List<Profession> professions;
```

**Comment by kollb** [comment]
Beim Löschen des Accounts dann auch
