### ISSUE TITLE
Clean up pom.xml

### ISSUE THREAD

**Issue by JanMalch** [JanMalch/kino#48]
- [x] ~Remove unused dependencies~ (https://github.com/JanMalch/kino/issues/48#issuecomment-504159695)
- [x] Properly manage version numbers
- [x] Properly manage scopes (see also: https://github.com/JanMalch/kino/pull/54#pullrequestreview-236043161)

**Comment by kollb** [comment]
Plugin Analyzer sagt es gibt keine unused dependencies

**Comment by kollb** [comment]
pom.xml is fine
