### ISSUE TITLE
Mehrere Reservierungen für einen Film von einem Account

### ISSUE THREAD

**Issue by JanMalch** [JanMalch/kino#79]
Sollte ein Account mehrere Reservierungen für einen Film machen können?

**Comment by kollb** [comment]
Ja. Wenn ich nur x Plätze reserviert habe und sich noch einer meldet, sollte er doch den auch nachreservieren dürfen.

**Comment by JanMalch** [comment]
Update fehlt auch noch, aber man kann aktuell auch zwei verschiedene Reservierungen für eine Vorstellung machen.

**Comment by kollb** [comment]
Das habe ich mich auch schon gefragt, ob wir ein Update brauchen. Wenn wir RL als Beispiel nehmen, dürfen wir das ja auch nicht.

**Comment by JanMalch** [comment]
Immutable Kino-Website. Keine Updates erlaubt 🎉

**Comment by MarekHohmann** [comment]
Ich kenn es auch so, dass man zwei Reservierungen für die gleiche Vorstellung machen kann. Es wird ja schon serverseitig sichergestellt, dass man keine bereits vergebenen Plätze reservieren kann.

Also Update könnte man tatsächlich in die Tonne hauen. Dann bräuchten wir nur NewReservation.

**Comment by JanMalch** [comment]
Also weder Admin noch Customer kann Reservierungen updaten.
Im Frontend kann ich noch ein Hinweis machen, ob man schon eine Reservierung für die Vorführung hat.

Man müsste dann jetzt `updateReservationById` rausnehmen und auch API im Frontend aktualisieren. Da wirds dann Fehler geben. Ist aber auch nix wildes.

**Comment by MarekHohmann** [comment]
ist die Frage, ob Admin und Customer das können sollen ... muss aber nicht unbedingt sein. Würde es rauslassen damit wir mal fertig werden

**Comment by kollb** [comment]
closed because of necessary feature
