### ISSUE TITLE
Presentation overview

### ISSUE THREAD

**Issue by JanMalch** [JanMalch/kino#93]
Filter presentations from the past in overview.

---

In der Hauptübersicht: die Filme werden halt anhand ihres Start- und Endedatums angezeigt. Ist verwirrend wenn der bis Juni läuft aber wir nur Vorstellungen bis Mitte Mai drin haben und der Film in jeder Woche angezeigt wird. Eventuell die Daten auf dem Movie rausnehmen und nur über die existierenden Vorstellungen anzeigen?

---

~"Aufführungen"~ -> "Vorführungen"

**Comment by kollb** [comment]
Hm ja, wäre glaub ich besser
